openapi: 3.0.0
info:
  title: comp3900_project
  contact: {}
  version: "1.0"
servers:
  - url: http://localhost:3000/api/v1
    variables: {}
paths:
  /auth/logout:
    get:
      tags:
        - Auth
      summary: logout
      operationId: logout
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
  /auth/login:
    post:
      tags:
        - Auth
      summary: login
      operationId: login
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/loginrequest"
                - example:
                    email: aooif@unsw.edu.au
            example:
              email: aooif@unsw.edu.au
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
  /users:
    get:
      tags:
        - User
      summary: Get All Users
      operationId: GetAllUsers
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
  /users/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The user ID
    get:
      tags:
        - User
      summary: Get Single User
      operationId: GetSingleUser
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
  /users/showMe:
    get:
      tags:
        - User
      summary: Show Current User
      operationId: ShowCurrentUser
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
  /rooms:
    get:
      tags:
        - Room
      summary: Get All Rooms
      operationId: GetAllRooms
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
    post:
      tags:
        - Room
      summary: Create Room
      operationId: CreateRoom
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
  /rooms/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The room ID
    get:
      tags:
        - Room
      summary: Get Single Room
      operationId: GetSingleRoom
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
    patch:
      tags:
        - Room
      summary: Update Room
      operationId: UpdateRoom
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
    delete:
      tags:
        - Room
      summary: Delete Room
      operationId: DeleteRoom
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
  /bookings/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The booking ID
    get:
      tags:
        - Booking
      summary: Get Single Booking
      operationId: GetSingleBooking
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
    delete:
      tags:
        - Booking
      summary: Delete Booking
      operationId: DeleteBooking
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
  /bookings/showAllMyBookings:
    get:
      tags:
        - Booking
      summary: get current users bookings
      operationId: getcurrentusersbookings
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
  /bookings:
    get:
      tags:
        - Booking
      summary: Get All Bookings
      operationId: GetAllBookings
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
    post:
      tags:
        - Booking
      summary: Create Booking
      operationId: CreateBooking
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/CreateBookingRequest"
                - example:
                    user: 666111538a5f81663714c636
                    room: 666d91548a5f81663714c666
                    start: 2024-07-21T14:34:21.373Z
                    duration: "3"
            example:
              user: 666111538a5f81663714c636
              room: 666d91548a5f81663714c666
              start: 2024-07-21T14:34:21.373Z
              duration: "3"
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
components:
  schemas:
    loginrequest:
      title: loginrequest
      required:
        - email
      type: object
      properties:
        email:
          type: string
      example:
        email: aooif@unsw.edu.au
    CreateBookingRequest:
      title: CreateBookingRequest
      required:
        - user
        - room
        - start
        - duration
      type: object
      properties:
        user:
          type: string
        room:
          type: string
        start:
          type: string
        duration:
          type: string
      example:
        user: 666111538a5f81663714c636
        room: 666d91548a5f81663714c666
        start: 2024-07-21T14:34:21.373Z
        duration: "3"
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
  - name: Auth
  - name: User
  - name: Room
  - name: Booking
